# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-06 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=35)),
                ('last_name', models.CharField(max_length=35)),
                ('prefix', models.CharField(max_length=5)),
                ('tel_number', models.CharField(max_length=11)),
                ('positin', models.CharField(max_length=35)),
                ('email', models.CharField(max_length=35)),
                ('picture', models.CharField(max_length=1000)),
            ],
        ),
    ]
