# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-06 20:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='positin',
            new_name='position',
        ),
    ]
